version: "3.9"

services:
  app:
    image: my-app
    ports:
      - 8000:8080
    environment:
      DRUPAL_HASH_SALT_FILE: /run/secrets/drupal_hash_salt

secrets:
  drupal_hash_salt: 
    name: drupal_hash_salt
    external: true
