version: "3.9"

services:
  app:
    image: my-app
    ports:
      - 8000:8080
    environment:
      DRUPAL_HASH_SALT_FILE: /run/secrets/drupal-hash-salt
    volumes:
      - volume:/workspace/.drupal/volume

secrets:
  drupal-hash-salt: 
    name: drupal-hash-salt
    external: true

volumes:
  volume:
